# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];

  #boot.blacklistedKernelModules = [ "snd-hda-intel" "snd-soc-skl" ];
  boot.blacklistedKernelModules = [ "snd-soc-skl" ];
  #boot.blacklistedKernelModules = [ "snd-hda-intel"];
  boot.kernelModules = [ "kvm-intel" "coretemp" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [ "i8042.nopnp=1" "i8042.dumbkbd=1" ];
  boot.loader.systemd-boot.enable = true;
  # hardware.opengl.extraPackages = with pkgs; [ 
  #     intel-compute-runtime 
  #     intel-media-driver # LIBVA_DRIVER_NAME=iHD
  #     vaapiIntel         # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
  #     vaapiVdpau
  #     libvdpau-va-gl

  # ];

     # options snd-intel-hda model=alc295-hp-x360
     # options snd slots=snd-hda-intel
   boot.extraModprobeConfig = ''
     options snd-intel-dspcfg dsp_driver=1
   '';
   boot.binfmt.emulatedSystems = [ "aarch64-linux" ];


  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5E8C-1E63";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0d139682-508d-4a08-b8c4-987991a20c52";
    fsType = "ext4";
  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.steam-hardware.enable = true;
  hardware.intelgpu.driver = "xe";

  # hardware.opentabletdriver.enable = true;
  hardware.bluetooth.enable = true;
  hardware.opengl = { enable = true; };

  hardware.pulseaudio.enable = false;
  networking.hostName = "spectre"; # Define your hostname.
  hardware.sensor.iio.enable = true;
  hardware.enableAllFirmware = true;
  services.hardware.bolt.enable = true;
#  hardware.opentabletdriver.enable = true;

}
