# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  nixos-hardware,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    nixos-hardware.nixosModules.common-cpu-intel
    nixos-hardware.nixosModules.common-pc-laptop
    # nixos-hardware.nixosModules.common-pc-laptop-acpi_call
    nixos-hardware.nixosModules.common-pc-laptop-ssd
  ];

  # allow cross building for pi
  boot.binfmt.emulatedSystems = ["aarch64-linux"];
  boot.binfmt.preferStaticEmulators = true;

  boot.initrd.availableKernelModules = [
    "nvme"
    "rtsx_pci_sdmmc"
    "sd_mod"
    "thunderbolt"
    "usb_storage"
    "vmd"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [];

  boot.blacklistedKernelModules = ["snd-soc-skl"];
  boot.extraModulePackages = [];
  boot.kernelModules = [
    "kvm-intel"
    "coretemp"
  ];
  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.kernelParams = [
    "i8042.nopnp=1"
    "i8042.dumbkbd=1"
  ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;
  # boot.extraModprobeConfig = ''
  #   options snd_hda_intel  dmic_detect=0 power-save=0
  # '';
  # boot.extraModprobeConfig = ''
  #   options snd_hda_intel dsp_driver=0  power-save=0
  # '';

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/data";
    fsType = "ext4";
  };

  hardware.bluetooth.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableAllFirmware = true;
  hardware.intelgpu.driver = "xe";
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;
  hardware.sensor.iio.enable = true;
  hardware.steam-hardware.enable = true;
  # hardware.opentabletdriver.enable = true;
  networking.hostName = "spectre"; # Define your hostname.
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  services.hardware.bolt.enable = true;
}
