# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/98e21973-32bf-4a30-9fc2-db50060f674c";
  boot.initrd.luks.devices."nixos".preLVM = false;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/99B1-F341";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/data";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."data".device = "/dev/disk/by-uuid/7b1cf9e3-da26-4c7a-89a2-1f150ad3b798";
  boot.initrd.luks.devices."data".preLVM = false;

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";


  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

}

